# Sample guardfile block for Guard::JSHaml
# You can use some options to change guard-jshaml configuration
# :output => 'public'                   set output directory for compiled files
# :input => 'src'                       set input directory with haml files
# :run_at_start => true                 compile files when guard starts
# :notifications => true                send notifictions to Growl/libnotify/Notifu
# :jshaml_options => {}    pass options to the haml_to_js engine

guard 'jshaml' do
  watch(/^.+(\.jshaml)/)
end
